### ISSUE TITLE
Fairness across multiple streams

### ISSUE THREAD

**Issue by Lupus** [anmonteiro/httpaf#41]
We ran into an issue with fairness when running multiple echo streams on one httpaf-based service. This problem boils down to one stream hogging all CPU power as reads never block on high data rates and event loop does not have a chance to run and schedule others. See https://github.com/ocsigen/lwt/issues/622 for more context.

In our custom Lwt adapter we workaround this by adding `Lwt_main.yield ()` after each read loop iteration along with increase of read buffer size to one megabyte, this way we yield once per each megabyte of data read, which gives good fairness and does not kill performance by endless epolls.

May be similar logic could be baked into Lwt adapter behind some configuration parameters?

**Comment by Lupus** [comment]
Actually after back-pressure feature has landed, adding `Lwt.pause()` inside `on_read` callback right before scheduling another read callback works as well as our forked Lwt adapter with vanilla httpaf, so we would probably settle on this approach, as it allows us to avoid patching&rebasing gluten upon each release.

**Comment by anmonteiro** [comment]
@Lupus I'm tempted to close this issue as a "won't fix", and instead recommend folks to use `Lwt.pause` inside their on_read handlers every N reads, like you do in your applications. What do you think?

**Comment by Lupus** [comment]
Yeah, sounds good to me!
