### ISSUE TITLE
Writer prematurely closes connection

### ISSUE THREAD

**Issue by Lupus** [anmonteiro/httpaf#76]
Stable repro on the latest `fork`:

```
$ git log -n 1                                                                                                                 
commit 19618b2158a9f8e64c6091b460db76a2144c1b49 (HEAD -> fork, origin/fork)
Merge: 99f3a00 bf79775
Author: Antonio Nuno Monteiro <anmonteiro@gmail.com>
Date:   Tue Jun 2 20:34:08 2020 -0700

    server_connection: call the error handler on EOF if the entire body hasn't been received (#75)                                                                           

    Also expose `Reqd.error_code`, which is useful to detect if the request handler has                                                                                      
    stopped reading (and fed EOF) because the request body ended abruptly.
```

To illustrate the problem one would need `nc` listening on a port on a separate terminal: `nc -l -p 10500`.

Build and run `lwt_post` example:

```
$ dune build examples/lwt/lwt_post.exe
$ echo -n "foobar" | _build/default/examples/lwt/lwt_post.exe -p 10500 127.0.0.1
Error handling response: Malformed response: unexpected eof
```

`lwt_post.exe` will hang. On the other terminal one would see:

```
$ nc -l -p 10500
POST / HTTP/1.1
content-length: 6
connection: close
host: 127.0.0.1

foobar
```

And `nc` will exit due to client closing the connection.

Correct behavior could be observed using `curl` instead of `lwt_post.exe` -- both `curl` and `nc` will hang, `nc` will wait for end of stream, and `curl` will wait for some response.

**Comment by Lupus** [comment]
According to bisect, this commit introduces the problem: df633d059195f398fbee2a10e4871e9d95dc6d57

**Comment by anmonteiro** [comment]
This seems to have been originally caused by #47, there's a fix in https://github.com/anmonteiro/gluten/pull/10

**Comment by Lupus** [comment]
Thanks @anmonteiro ! Fix works as expected.
